### ISSUE TITLE
Could you please add "wallet/convert" method ?

### ISSUE THREAD

**Issue by lrlrlrlr** [paxful/api-docs#37]
Could you please add "wallet/convert" method? So we can convert BTC to USDT and ETH. 
The convert function is very useful to the trader who is holding different crypto.

Thanks!

**Comment by sergeil** [comment]
Hey @lrlrlrlr .

Thank you for reaching out.

This endpoint is going to become available approx by end of June.

**Comment by lrlrlrlr** [comment]
Thanks for the information!

**Comment by lrlrlrlr** [comment]
Hi, any update for this endpoint?

**Comment by sergeil** [comment]
Hey, @lrlrlrlr!

Sorry for keeping you wait. Holidays kicked in a thus some planned work got delayed. The good news is that the feature is ready and is in QA now, so if all goes well then it is going to be released end of this/beginning of the next week.

Let's keep this ticket open, I will close it once the feature is released.

Thanks.

**Comment by sergeil** [comment]
Hey, @lrlrlrlr .

wallet/convert along with other required endpoints have been released. Closing this thread now.

Feel free at any time to suggest improvements, additional endpoints that you'd need.
